hashicorp/hcp-terraform-operator

README.md
charts/terraform-cloud-operator/Chart.yaml
charts/terraform-cloud-operator/templates/clusterrole.yaml
config/rbac/role.yaml
controllers/module_controller.go
controllers/workspace_controller.go

This PR updates RBAC permission for both controllers to allow them to update `ConfigMaps` and `Secrets`.
Nothing has changed externally.

Update RBAC permission

---

.github/workflows/integration-test.yaml

This PR adds GHA workflow to run integration tests.
Nothing has changed externally.

Add GHA workflow: integration tests

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/question.md

This PR add issue templates to the repo.

Add issue templates

---

charts/terraform-cloud-operator/templates/deployment.yaml

A new version `v0.13.1` of `kube-rbac-proxy` image was issued with a security fix for `CVE-2022-27191`. More details in their [release](https://github.com/brancz/kube-rbac-proxy/releases/tag/v0.13.1).
N/A
```release-note
[ENHANCEMENT] Bump `kube-rbac-proxy` image to `v0.13.1`.
```
- https://github.com/brancz/kube-rbac-proxy/releases/tag/v0.13.1
* If you are interested in working on …

[TK-2048] 🐛 Update `kube-rbac-proxy` image to version `v0.13.1`

---

README.md

Update ReadME.md to include experimental copy

---

README.md
docs/agentpool.md
docs/api-reference.md
docs/installation.md
docs/module.md
docs/usage.md
docs/workspace.md

This PR updated the repository documentation:
- split current `README.md` into smaller chunks and move them to `docs/`
- Add `Usage` documentation for a new controller `AgentPool`
N/A
```release-note
NONE
```
- Depends on: https://github.com/hashicorp/terraform-cloud-operator/pull/28
- Depends on: https://github.com/hashicorp/terraform-cloud-operator/pull/29
- Depends on: https://github.com/hashicorp/terraform-cloud-operator/pull/32 …

📖 Update repository documentation

---

.github/workflows/codeql-analysis.yml

Add CodeQL analysis workflow to the repository.
N/A
```release-note
NONE
```
N/A

🤖 Add CodeQL analysis workflow

---

Makefile
charts/terraform-cloud-operator/crds/app.terraform.io_agentpools.yaml
charts/terraform-cloud-operator/crds/app.terraform.io_modules.yaml
charts/terraform-cloud-operator/crds/app.terraform.io_workspaces.yaml
charts/terraform-cloud-operator/templates/deployment.yaml
config/crd/bases/app.terraform.io_agentpools.yaml
config/crd/bases/app.terraform.io_modules.yaml
config/crd/bases/app.terraform.io_workspaces.yaml
docs/api-reference.md
docs/config.yaml

This PR bumps Kubernetes ecosystem tools versions. Such updates are not captured by dependabot.
N/A
```release-note
NONE
```
N/A

🌱 Bump Kubernetes ecosystem tools versions

---

README.md
docs/agentpool.md
docs/faq.md

This PR updates the `AgentPool` documentation and add initial FAQ.
N/A
```release-note
docs: Update the `AgentPool` documentation and add FAQ.
```
N/A

📖 Update Agent Pool controller documentation and add initial FAQ

---

README.md
api/v1alpha2/agentpool_types.go
api/v1alpha2/module_types.go
api/v1alpha2/workspace_types.go
config/crd/bases/app.terraform.io_agentpools.yaml
config/crd/bases/app.terraform.io_modules.yaml
config/crd/bases/app.terraform.io_workspaces.yaml
docs/api-reference.md
docs/faq.md
docs/features.md

This PR adds a list of supported features and update FAQ with a few more questions.
N/A
```release-note
NONE
```
N/A

📖 Update the Operator documentation and FAQ

---

controllers/agentpool_controller_test.go

This PR makes the `AgentPool` controller tests more reliable.
N/A
```release-note
NONE
```
N/A

🚀 Update Agent Pool tests

---

.gitignore
charts/terraform-cloud-operator/templates/deployment.yaml
charts/terraform-cloud-operator/values.yaml
docs/faq.md
docs/installation.md

The operator currently defaults to connecting to the public TFC endpoint (app.terraform.io). This change introduces a Helm chart variable that allows users to define a custom API endpoint, which will allow the operator to work with TFE installations as well. 
It makes use of the fact that `go-tfe` observes the TFE_ADDRESS environment variable as a way to set a custom endpoint.
https://pkg.go.dev/github.com/hashicorp/go-tfe@v1.17.0#section-readme
```release-note
* allow configuring TFE endpoints via "operator.tfe_address" Helm value
```
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and …

TFECO-1485: Allow setting TFE_ADDRESS via chart variable

---

README.md
docs/faq.md
docs/metrics.md

Add Metrics documentation.
N/A
```release-note
DOCS: add Metrics documentation.
```
N/A

📖 Add Metrics documentation

---

charts/terraform-cloud-operator/templates/deployment.yaml

When no "tfeAddress" value is set, don't render an empty `env:` attribute in the Deployment pod template.
```release-note
NONE
```

Don't include empty env: attribute in Deployment template

---

CHANGELOG.md
README.md
charts/terraform-cloud-operator/Chart.yaml

Release `v2.0.0-beta3`.
N/A
```release-note
NONE
```
N/A

🎉 v2.0.0-beta3

---

.github/workflows/docker-image-scan.yml

🤖 Add scan Docker image for vulnerabilities action

---

.github/workflows/docker-image-scan.yml

Fix Docker image scan GH action.
N/A.
```release-note
NONE
```
N/A.

🤖 Fix Docker image scan GH action

---

README.md
api/v1alpha2/module_types.go
api/v1alpha2/workspace_types.go
docs/api-reference.md
docs/examples/README.md
docs/examples/agentPool-basic.yaml
docs/examples/module-basic.yaml
docs/examples/workspace-basic.yaml
docs/examples/workspace-runTriggers.yaml
docs/examples/workspace-terraformVersion.yaml
docs/faq.md
docs/module.md
docs/workspace.md

This PR brings the following changes:
- Update `Module` and `Workspace` documentation.
- Update `FAQ`.
- Update `API Reference`.
- Add examples for controllers to demonstrate feature usage.
N/A.
```release-note
`docs`: Update controllers documentation.
`docs`: Update FAQ.
`docs`: Update API Reference.
`docs`: Add examples.
```
N/A.
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help …

📖 Update documentation

---

controllers/agentpool_controller.go

Fix a small typo in a log message

---

.github/workflows/hc-copywrite.yml

Update copyright workflow.
N/A.
```release-note
NONE
```
N/A.

🤖 Update copyright workflow

---

charts/terraform-cloud-operator/Chart.yaml
charts/terraform-cloud-operator/templates/clusterrole.yaml
controllers/agentpool_controller.go

The operator is failing when installing from the chart as the RBAC role doesn't allow access to the Deployments API. 
```release-note
NONE
```

Update chart RBAC to allow access to Deployments

---

charts/terraform-cloud-operator/templates/clusterrole.yaml
config/rbac/role.yaml
controllers/agentpool_controller.go

RBAC for Deployments should use `apps` API group

---

.github/dependabot.yml

Update dependabot schedule.
N/A.
```release-note
NONE
```
N/A.

🤖 Update dependabot schedule

---

README.md

Add Docker pull badge to the README.md file to see the number of pulls from the Docker hub.
N/A.
```release-note
NONE
```
N/A.

Add Docker pull badge

---

CHANGELOG.md
README.md
charts/terraform-cloud-operator/Chart.yaml

Cutting a new release with the RBAC fixes.
```release-note
NONE
```

v2.0.0-beta5

---

docs/agentpool.md

Remove note from Agent Pools docs

---

docs/installation.md

Update Helm chart install doc with notes related to the beta version.
N/A.
```release-note
NONE
```
N/A.

📖 Update Helm chart install doc

---

.github/workflows/jira-issues.yaml
.github/workflows/jira-pr.yaml

JIRA GHA Integration

---

Makefile
controllers/agentpool_controller.go
controllers/agentpool_controller_autoscaling.go
controllers/agentpool_controller_test.go

Fix failing test for autoscaling

---

controllers/agentpool_controller_autoscaling.go

fix min/max replicas ordering in autoscaler

---

charts/terraform-cloud-operator/README.md
docs/faq.md

Update the FAQ and Helm Readme file with upgrade recommendations to ensure a smooth update process.
N/A.
```release-note
NONE.
```
- https://github.com/hashicorp/terraform-cloud-operator/issues/324
- https://github.com/hashicorp/terraform-cloud-operator/pull/309#issuecomment-1902869817
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this …

📖 Update FAQ

---

.changes/unreleased/ENHANCEMENTS-326-20240213-124424.yaml
charts/terraform-cloud-operator/README.md
charts/terraform-cloud-operator/templates/deployment.yaml
charts/terraform-cloud-operator/values.yaml

- Adds `imagePullSecrets` to allow users to specify credentials for pulling down images. Useful when images used by this chart, are mirrored into a private registry.
Chart parses correctly as shown below. 
```sh
$ helm template . --set-json 'imagePullSecrets=[{"name": "cred"}, {"name": "test"}]' | yq  'select(document_index == 9) | .spec.template.spec'
imagePullSecrets:
- name: cred
- name: test
containers:
- name: manager
image: hashicorp/terraform-cloud-operator:2.2.0
...
```
```release-note
Adds `imagePullSecrets` to allow users to specify credentials for pulling down images.
```
- Fixes: https://github.com/hashicorp/terraform-cloud-operator/issues/161
* Please do not leave "+1" …

Add imagePullSecrets support

---

controllers/workspace_controller_notifications_test.go

This PR fixes Workspace Notification tests.
Tests:
- https://github.com/hashicorp/terraform-cloud-operator/actions/runs/8069855010
- https://github.com/hashicorp/terraform-cloud-operator/actions/runs/8069863912
N/A.
N/A.

🐛 Fix Workspace Notification tests

---

controllers/agentpool_controller_test.go
controllers/project_controller_team_access.go
controllers/workspace_controller.go
controllers/workspace_controller_notifications.go
controllers/workspace_controller_run_tasks.go
controllers/workspace_controller_team_access.go
controllers/workspace_controller_variables.go

Remove unused functions and arguments.
- https://github.com/hashicorp/terraform-cloud-operator/actions/runs/8157113923
- https://github.com/hashicorp/terraform-cloud-operator/actions/runs/8157114794
N/A.
N/A.

🧹 Remove unused functions and arguments

---

.github/workflows/build.yml

Remove `v` prefix from LD_FLAGS.
N/A.
N/A.

🛠️ Remove `v` prefix from LD_FLAGS

---

go.mod
go.sum

[Security] Bump indirect dependencies.
N/A.
N/A.

🌱 Bump indirect dependencies

---

docs/migration/crds/workspaces_patch_a.yaml
docs/migration/crds/workspaces_patch_b.yaml

Fix migration patches.
N/A.
Close: https://github.com/hashicorp/terraform-cloud-operator/issues/338

🐛 Fix migration patches

---

.github/CODEOWNERS

🤖 Update CODEOWNERS

---

.github/CODEOWNERS

🛠️ Update CODEOWNERS

---

README.md

📖 Update README

---

controllers/workspace_controller_agents_test.go
controllers/workspace_controller_notifications_test.go
controllers/workspace_controller_outputs_test.go
controllers/workspace_controller_projects_test.go
controllers/workspace_controller_remote_state_sharing_test.go
controllers/workspace_controller_run_tasks_test.go
controllers/workspace_controller_run_triggers_test.go
controllers/workspace_controller_runs_test.go
controllers/workspace_controller_sshkey_test.go
controllers/workspace_controller_team_access_test.go
controllers/workspace_controller_test.go
controllers/workspace_controller_variables_test.go
controllers/workspace_controller_vcs_test.go

Update Workspace controller tests to generate unique object names.
- [![E2E on HCP Terraform Operator](https://github.com/hashicorp/hcp-terraform-operator/actions/workflows/end-to-end-tfc.yaml/badge.svg?branch=update-workspace-tests&event=workflow_dispatch)](https://github.com/hashicorp/hcp-terraform-operator/actions/workflows/end-to-end-tfc.yaml?query=branch:update-workspace-tests)
- [![E2E on HCP Terraform Operator [Helm]](https://github.com/hashicorp/hcp-terraform-operator/actions/workflows/helm-end-to-end-tfc.yaml/badge.svg?branch=update-workspace-tests&event=workflow_dispatch)](https://github.com/hashicorp/hcp-terraform-operator/actions/workflows/helm-end-to-end-tfc.yaml?query=branch:update-workspace-tests)
- [![E2E on Terraform …

🛠️ Update Workspace controller tests

---

.changes/unreleased/ENHANCEMENTS-451-20240806-184914.yaml
charts/hcp-terraform-operator/README.md
charts/hcp-terraform-operator/templates/deployment.yaml
charts/hcp-terraform-operator/values.yaml

Add the Ability to Customize the priorityClassName for hcp-terraform-operator deployment
`values.yaml`
```
priorityClassName: "critical-workloads"
```
N/A

🚀Add the Ability to Customize the priorityClassName

---

.github/workflows/dependabot-pr.yaml

Change `on.push` to `on.pull_request_target` for Dependabot PR workflow: https://github.com/dependabot/dependabot-core/issues/3253#issuecomment-852541544
N/A.
N/A.

🤖 Update dependabot PR workflow

---

.changes/unreleased/ENHANCEMENTS-487-20240917-131255.yaml
controllers/agentpool_controller.go
controllers/agentpool_controller_test.go
controllers/agentpool_controller_tokens.go

Update agent token reconciliation logic to reduce the number of API calls that the controller does. On top of that, update the defer action to avoid making unnecessary API calls.
- [![E2E on HCP Terraform Operator](https://github.com/hashicorp/hcp-terraform-operator/actions/workflows/end-to-end-tfc.yaml/badge.svg?branch=update-agent-pool-reconciliation-logic&event=workflow_dispatch)](https://github.com/hashicorp/hcp-terraform-operator/actions/workflows/end-to-end-tfc.yaml?query=branch:update-agent-pool-reconciliation-logic)
- [![E2E on HCP Terraform Operator [Helm]](https://github.com/hashicorp/hcp-terraform-operator/actions/workflows/helm-end-to-end-tfc.yaml/badge.svg?branch=update-agent-pool-reconciliation-logic&event=workflow_dispatch)](https://github.com/hashicorp/hcp-terraform-operato …

🚀 Update Agent Pool reconciliation logic

---

.changes/unreleased/ENHANCEMENTS-477-20240821-134240.yaml
controllers/workspace_controller_notifications.go
controllers/workspace_controller_notifications_test.go

This PR updates Workspace Notifications reconciliation logic to reduce the number of API calls.
- [![E2E on HCP Terraform Operator](https://github.com/hashicorp/hcp-terraform-operator/actions/workflows/end-to-end-tfc.yaml/badge.svg?branch=update-notifications-reconciliation&event=workflow_dispatch)](https://github.com/hashicorp/hcp-terraform-operator/actions/workflows/end-to-end-tfc.yaml?query=branch:update-notifications-reconciliation)
- [![E2E on HCP Terraform Operator [Helm]](https://github.com/hashicorp/hcp-terraform-operator/actions/workflows/helm-end-to-end-tfc.yaml/badge.svg?branch=update-notifications-reconciliation&event=workflow_dispatch)](https://github.com/hashicorp/hcp-terraform-operator/actions/workflows/helm-end-to-end-tfc.yaml?query=branch:update-notifications-reconciliatio …

🚀 Update Workspace Notifications reconciliation logic

---

.changes/unreleased/FEATURES-489-20241017-094021.yaml
api/v1alpha2/module_types.go
api/v1alpha2/workspace_types.go
api/v1alpha2/workspace_validation.go
api/v1alpha2/workspace_validation_test.go
charts/hcp-terraform-operator/crds/app.terraform.io_modules.yaml
charts/hcp-terraform-operator/crds/app.terraform.io_workspaces.yaml
config/crd/bases/app.terraform.io_modules.yaml
config/crd/bases/app.terraform.io_workspaces.yaml
controllers/module_controller.go
controllers/workspace_controller_deletion_policy.go
controllers/workspace_controller_deletion_policy_test.go
docs/api-reference.md

This PR adds `destroy` deletion policy.
- [![E2E on HCP Terraform Operator](https://github.com/hashicorp/hcp-terraform-operator/actions/workflows/end-to-end-tfc.yaml/badge.svg?branch=add-destroy-deletion-policy&event=workflow_dispatch)](https://github.com/hashicorp/hcp-terraform-operator/actions/workflows/end-to-end-tfc.yaml?query=branch:add-destroy-deletion-policy)
- [![E2E on HCP Terraform Operator [Helm]](https://github.com/hashicorp/hcp-terraform-operator/actions/workflows/helm-end-to-end-tfc.yaml/badge.svg?branch=add-destroy-deletion-policy&event=workflow_dispatch)](https://github.com/hashicorp/hcp-terraform-operator/actions/workflows/helm-end-to-end-tfc.yaml?query=branch:add-destroy-deletion-policy)
- [![E2E on Terraform Enterprise](https://github.com/hashicorp/hcp-terraform-operator …

🚀 Add `destroy` deletion policy

---

.github/workflows/build.yml

Update actions in the build workflow.
N/A.
N/A.

🤖 Update actions in the build workflow

---

api/v1alpha2/agentpool_types.go
api/v1alpha2/workspace_types.go
charts/hcp-terraform-operator/crds/app.terraform.io_agentpools.yaml
charts/hcp-terraform-operator/crds/app.terraform.io_workspaces.yaml
config/crd/bases/app.terraform.io_agentpools.yaml
config/crd/bases/app.terraform.io_workspaces.yaml
docs/api-reference.md

Update API reference to align with the developer portal.
N/A.
N/A.

📖 Update API reference

---

.changes/unreleased/DEPENDENCIES-531-20241129-220317.yaml
charts/hcp-terraform-operator/README.md
charts/hcp-terraform-operator/values.yaml

🌱 Bump kube-rbac-proxy from 0.18.1 to 0.18.2.
- [![E2E on HCP Terraform Operator](https://github.com/hashicorp/hcp-terraform-operator/actions/workflows/end-to-end-tfc.yaml/badge.svg?branch=bump-kube-rbac-proxy&event=workflow_dispatch)](https://github.com/hashicorp/hcp-terraform-operator/actions/workflows/end-to-end-tfc.yaml?query=branch:bump-kube-rbac-proxy)
- [![E2E on HCP Terraform Operator [Helm]](https://github.com/hashicorp/hcp-terraform-operator/actions/workflows/helm-end-to-end-tfc.yaml/badge.svg?branch=bump-kube-rbac-proxy&event=workflow_dispatch)](https://github.com/hashicorp/hcp-terraform-operator/actions/workflows/helm-end-to-end-tfc.yaml?query=branch:bump-kube-rbac-proxy)
- [![E2E on Terraform Enterprise](https://github.com/hashicorp/hcp-terraform-operator/actions/workflows/end …

🌱 Bump kube-rbac-proxy from 0.18.1 to 0.18.2

---

charts/hcp-terraform-operator/templates/clusterrole.yaml

Update Helm chart cluster role template.
- [![E2E on HCP Terraform Operator](https://github.com/hashicorp/hcp-terraform-operator/actions/workflows/end-to-end-tfc.yaml/badge.svg?branch=update-helm-rbac&event=workflow_dispatch)](https://github.com/hashicorp/hcp-terraform-operator/actions/workflows/end-to-end-tfc.yaml?query=branch:update-helm-rbac)
- [![E2E on HCP Terraform Operator [Helm]](https://github.com/hashicorp/hcp-terraform-operator/actions/workflows/helm-end-to-end-tfc.yaml/badge.svg?branch=update-helm-rbac&event=workflow_dispatch)](https://github.com/hashicorp/hcp-terraform-operator/actions/workflows/helm-end-to-end-tfc.yaml?query=branch:update-helm-rbac)
- [![E2E on Terraform Enterprise](https://github.com/hashicorp/hcp-terraform-operator/actions/workflows/end-to-end-tfe.yaml/badg …

⎈ Update Helm chart cluster role template

---

Dockerfile
charts/test/go.mod
go.mod

🌱 Bump Go version to 1.24.2.
N/A.
N/A.

🌱 Bump Go version to 1.24.2

---

.changes/2.9.0.md
CHANGELOG.md

Add missed entry into v2.9.0 changelog.
N/A.
N/A.

✨ Update v2.9.0 changelog

---

charts/hcp-terraform-operator/README.md
charts/hcp-terraform-operator/README.md.gotmpl

Update the Helm chart Readme with 2.9.0 update instructions.
N/A.
N/A.

📖 Update Helm chart Readme

---

.github/workflows/end-to-end-tfc.yaml
.github/workflows/end-to-end-tfe.yaml
.github/workflows/helm-end-to-end-tfc.yaml
.github/workflows/helm-end-to-end-tfe.yaml

N/A.
N/A.
Update GH actions to run them on changes in the controllers code.
N/A.
N/A.

🤖 Update GH actions

---

docs/faq.md

If a change needs to be reverted, we will publish an updated version of the library.

 📖 Customer Resource -> Custom Resource in FAQ

---

.changes/unreleased/DEPENDENCIES-640-20250919-114007.yaml
charts/hcp-terraform-operator/README.md
charts/hcp-terraform-operator/values.yaml

If a change needs to be reverted, we will publish an updated version of the library.
Bump kube-rbac-proxy from 0.19.1 to 0.20.0.
- [![E2E on HCP Terraform Operator](https://github.com/hashicorp/hcp-terraform-operator/actions/workflows/end-to-end-tfc.yaml/badge.svg?branch=bump-kube-rbac-proxy&event=workflow_dispatch)](https://github.com/hashicorp/hcp-terraform-operator/actions/workflows/end-to-end-tfc.yaml?query=branch:bump-kube-rbac-proxy)
- [![E2E on HCP Terraform Operator [Helm]](https://github.com/hashicorp/hcp-terraform-operator/actions/workflows/helm-end-to-end-tfc.yaml/badge.svg?branch=bump-kube-rbac-proxy&event=workflow_dispatch)](https://github.com/hashicorp/hcp-t …

🌱 Bump kube-rbac-proxy from 0.19.1 to 0.20.0
