hashicorp/hcp-terraform-operator

controllers/module_controller.go, controllers/module_controller_outputs.go, controllers/module_controller_test.go, controllers/suite_test.go, controllers/workspace_controller.go, controllers/workspace_controller_agents_test.go, controllers/workspace_controller_outputs.go, controllers/workspace_controller_outputs_test.go, controllers/workspace_controller_remote_state_sharing_test.go, controllers/workspace_controller_run_triggers_test.go, controllers/workspace_controller_sshkey_test.go, controllers/workspace_controller_team_access_test.go, controllers/workspace_controller_test.go, controllers/workspace_controller_variables_test.go, controllers/workspace_controller_vcs_test.go
This PR addresses intermittent race condition issues in the `Workspace` and `Module` controllers when they create or update outputs. The issue happens when the ongoing Run is finished while the operator is reconciling `Workspace` or `Module`. In this case, method `reconcileOutputs` has outdated information about `CurrentStateVersion` and either does not create related `ConfigMap` or `Secret` or does not update them with the recent changes. If that happens, the outputs will remain outdated until the next Run happens.
This PR adds an additional API call to get an updated TFC Workspace item when `Run` finishes between the time when a new reconciliation starts and synchronizes outputs. The method `reconcileOutputs` now is the one responsible for updating the `Status` of the relevant …
=> 🐛 [TK-2026] Fix race condition in `Workspace` and `Module` outputs

Makefile, docs/config.yaml
This PR adds a new target `docs` to Makefile to automatically manage API reference documentation for CRD. It uses [this](https://github.com/elastic/crd-ref-docs) project for that purpose. The new target is also a part of the `manifest` one. That guarantees that API reference documentation will be constantly updated together with changes in CRDs.
```console
$ make docs
GOBIN=/home/user/terraform-cloud-operator/bin go install github.com/elastic/crd-ref-docs@v0.0.8
/home/user/terraform-cloud-operator/bin/crd-ref-docs --renderer=markdown --source-path ./api/v1alpha2/ --config=./docs/config.yaml --output-path ./docs/api-reference.md
2022-12-08T10:38:43.644+0100	INFO	crd-ref-docs	Loading configuration	{"path": "./docs/config.yaml"}
2022-12-08T10:38:43.644+0100	INFO	crd-ref-docs	Processing …
```
=> [TK-2027] 📖 Add API reference documentation generator

controllers/agentpool_controller_test.go, controllers/agentpool_controller_tokens.go
This PR fixes an issue when manually created agent tokens are not removed from Agent Pool during the reconciliation.
N/A
```release-note
`AgentPool`: fix an issue when manually created agent tokens are not removed from Agent Pool during the reconciliation.
```
N/A
* If you are …
=> 🐛 Fix an issue when manually created agent tokens are not removed

.github/workflows/codeql-analysis.yml, .github/workflows/end-to-end-tests.yaml, .github/workflows/markdown-link-check.yaml, .github/workflows/pr-labeler.yml
This PR updates GitHub workflows to use pinned commit hash versions of actions according to the security recommendations:
- https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepsuses
- https://michaelheap.com/improve-your-github-actions-security/
- https://michaelheap.com/ensure-github-actions-pinned-sha/
N/A
```release-note
NONE
```
N/A
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues …
=> 🤖 Update GitHub workflows to use pinned commit hash versions

controllers/module_controller_test.go, controllers/module_controller_workspace.go
This PR fixes an issue when the Module CR fails if it refers to Workspace by ID and updates tests to catch this scenario.
N/A.
```release-note
`Module`: Fix an issue when the Module CR fails if it refers to Workspace by ID.
```
N/A.
* If you are interested in working on this …
=> 🐛 Fix an issue when the Module cannot get Workspace by ID

.github/workflows/end-to-end-tfc.yaml, .github/workflows/end-to-end-tfe.yaml, controllers/module_controller_test.go, controllers/suite_test.go
This PR adds a new GH workflow to run E2E tests on the TFE instance.
N/A.
```release-note
`operator`: add a new GH workflow to run tests on the TFE instance.
```
N/A.
=> 🤖 Add E2E workflow to run on TFE

.github/CODEOWNERS
Grant ownership to some files and directories to the release engineering team.
N/A.
```release-note
NONE
```
N/A.
=> Update the CODEOWNERS file with the release engineering team

Dockerfile
Fix an issue with the `ENTRYPOINT` in the Dockerfile and incorrect path when `COPY` the binary. In addition, remove unused `ARG` and add the `WORKDIR` layer for clarity.
N/A.
```release-note
NONE
```
N/A.
* If you are interested in working on this issue or have submitted a pull …
=> 🐛 Fix `ENTRYPOINT` and `COPY` layers in the Dockerfile

Makefile, charts/terraform-cloud-operator/crds/app.terraform.io_agentpools.yaml, charts/terraform-cloud-operator/crds/app.terraform.io_modules.yaml, charts/terraform-cloud-operator/crds/app.terraform.io_workspaces.yaml, config/crd/bases/app.terraform.io_agentpools.yaml, config/crd/bases/app.terraform.io_modules.yaml, config/crd/bases/app.terraform.io_workspaces.yaml
- Bump Kustomize from 4.5.7 to 5.0.1
- Bump Kubernetes EnvTest from 1.26.0 to 1.26.1
- Update CRDs to reflect the actual version of the controller-tools in annotations
N/A.
```release-note:dependencies
Bump Kustomize from `4.5.7` to `5.0.1`
Bump Kubernetes EnvTest from `1.26.0` to `1.26.1`
```
N/A.
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers …
=> 🌱 Bump Kustomize and Envtest dependencies

.github/workflows/pr-labeler.yml
Update GHA `pr-labeler.yml` to align the action name with the TSCCR.
N/A.
```release-note
NONE
```
N/A.
=> 🤖 Update pr-labeler.yml

charts/terraform-cloud-operator/templates/ca_secret.yaml, charts/terraform-cloud-operator/templates/deployment.yaml, charts/terraform-cloud-operator/values.yaml, docs/installation.md
Some TFE installations use TLS certificates signed by private Certificate Authorities.
In order for the Operator to work with these installations, it needs to be configured with custom CA bundles that include the root certificates for such private CAs. These are installed through Helm, as a ConfigMap object mounted as a volume on top of the container image for the Operator process.
```
$ helm install \
demo hashicorp/terraform-cloud-operator \
--namespace tfc-operator-system \
--create-namespace \
--set customCAcertificates=letsencrypt-bundle.crt
```
```release-note
* Add Helm chart value to configure custom CA certificates
```
TFECO-3990
* Please do not leave "+1" or other comments …
=> Add Helm chart value to configure custom CA certificates

.github/test-infra/tfe/README.md, .github/test-infra/tfe/initial-admin/admin.tf, .github/test-infra/tfe/main.tf, .github/test-infra/tfe/outputs.tf, .github/test-infra/tfe/terraform.auto.tfvars, .github/test-infra/tfe/variables.tf, .github/test-infra/tfe/versions.tf, .gitignore
This add the ability to provision a TFE instance on Google Cloud to serve as a target for testing.
```release-note
NONE
```
=> Add TF configuration for provisioning TFE test instance

CHANGELOG.md, controllers/module_controller.go
This PR removed the automatically apply method from the `Module` when a new Run is executed. Instead, the apply method is now inherited from the Workspace in which the Run is executed.
N/A.
```release-note
`Module`: The Run now adopts the apply method of the Workspace in which it is executed. If the apply method is set to 'manual', the Run will remain on hold until it receives manual approval or rejection for the application or cancellation of the Run.
```
- Fixes: https://github.com/hashicorp/terraform-cloud-operator/issues/83
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not …
=> 🚀 Remove auto apply from Run to inherit it from the Workspace

.github/workflows/build.yml
This PR updates the `build` workflow by adding a new preview Docker tag based on `github.sha`.
N/A.
```release-note
NONE
```
N/A.
=> 🤖 Update `build` workflow

.github/workflows/build.yml
Bump up GHA `hashicorp/actions-docker-build` from `1.3.4` to `1.5.0`.
N/A.
```release-note
NONE
```
- Fixes: https://github.com/hashicorp/terraform-cloud-operator/issues/176
* If you are interested in working on this issue or have submitted a pull request, please leave a …
=> Bump up GHA hashicorp/actions-docker-build from 1.3.4 to 1.5.0

CHANGELOG.md, README.md, RELEASING.md, scripts/release-date.sh
This PR has the following changes:
- Add a new script `scripts/release-date.sh` that aims to replace `UNRELEASED` with the current date in the `CHANGELOG.md` file.
- Update the `RELEASING.md` file.
- Correct the release date of `2.0.0-beta6` in the `CHANGELOG.md` file.
- Remove `Install beta version` and `Upgrade beta version` sections from the documentation.
N/A.
```release-note
NONE
```
N/A.
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull …
=> 📖 Update the Releasing guide

.github/workflows/build.yml, CHANGELOG.md
Fix an issue when the `manager` binary is built dynamically linked for the `amd64` platform and thus doesn't execute.
Here is how the binary looks like now:
```console
$ file manager
manager: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, Go BuildID=6t7_Om9mjcdHWg5nl9dY/rwFCLkKjqObWsc7KzI7v/_FJeR4ElG29aEmXTBP2e/rcJTYNWa_iZQAwkP11cA, with debug_info, not stripped
```
And since we use `distroless` it can't be executed because `/lib64/ld-linux-x86-64.so.2` doesn't exist in this image.
Here is how the file looks like with this fix:
```console
$ file manager
manager: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, Go BuildID=IbLk7KklHR72DlNfXW8b/IyNUnfopeH6XQBu5tQnG/swXq8XmOqairktuEMVYO/Di11ccuyOMrVlObJUf …
```
=> 🤖 Update GHA workflow `build`

CHANGELOG.md, api/v1alpha2/workspace_types.go, charts/terraform-cloud-operator/crds/app.terraform.io_workspaces.yaml, config/crd/bases/app.terraform.io_workspaces.yaml, controllers/workspace_controller.go, controllers/workspace_controller_test.go, docs/faq.md, docs/migration/crds/workspaces_patch_a.yaml, docs/migration/crds/workspaces_patch_b.yaml, main.go
Add a new field to the `status` to reflect the Terraform version utilized in the Workspace.
This PR includes the following changes:
- Update FAQ regarding the Terraform version utilized in the Workspace.
- Add Terraform version utilized in the Workspace to the status: `status.TerraformVersion`.
- Fix an issue when the Operator couldn't start on a local machine during development. Introduced in https://github.com/hashicorp/terraform-cloud-operator/pull/185.
```console
$ kubectl get workspace this -o yaml
...
status:
observedGeneration: 1
runStatus: {}
terraformVersion: 1.5.1
updateAt: 1688463765
workspaceID: ws-XpQnRpW81rnJMGob
```
```release-note
`Workspace`: add Terraform version …
```
=> 🚀 Add `status.TerraformVersion`

controllers/agentpool_controller_autoscaling.go
When there are no agents available to pick up a run the status of the runs are pending. This PR adds additional statuses to trigger a scaling event; `plan_queued` and `apply_queued`.
Saving resource in Kubernetes by scaling down to 0 when there are no runs pending.
```release-note
Support autoscaling agents to 0 replicas
```
N/A
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the …
=> 🚀 Support autoscaling agents to 0 replicas

controllers/agentpool_controller_autoscaling.go
Changes `pendingRuns` to `queueDepth` since we are not just looking at the pending status.
```release-note
NONE
```
=> Some better naming for autoscaler functions

CHANGELOG.md, charts/terraform-cloud-operator/templates/deployment.yaml
The helm charts `deployment.yaml` includes a `name` key on the container spec twice. Typically this seems to be fine when using helm and applying it to Kubernetes but this causes problems if you want to use Kustomize to apply additional patches.
I'm not entirely sure the container name needs to be based on the chart name `{{ .Chart.Name }}` so I've just set this as `manager`.
N/A.
```release-note
`Helm Chart`: fix an issue with the Deployment template in the Helm chart where `name` in path `spec.template.spec.containers[0]` was duplicated.
```
N/A.
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue …
=> 🐛 Remove duplicate key `name` in the Helm chart's Deployment template

CHANGELOG.md, charts/terraform-cloud-operator/templates/deployment.yaml, charts/terraform-cloud-operator/values.yaml, controllers/agentpool_controller.go, controllers/module_controller.go, controllers/workspace_controller.go
```console
$ helm install demo hashicorp/terraform-cloud-operator --set operator.skipTLSVerify=true
$ helm upgrade demo hashicorp/terraform-cloud-operator --set operator.skipTLSVerify=true
```
```release-note
`Operator`: Add the ability to skip TLS certificate validation for communication between the Operator and the TFC/E endpoint. A new environment variable `TFC_TLS_SKIP_VERIFY` should be set to `true` to skip the validation. Default: `false`.
`Helm Chart`: Add a new parameter `operator.skipTLSVerify` to configure the ability to skip TLS certificate validation for communication between the Operator and the TFC/E endpoint. Default: `false`.
```
N/A.
* Please do not leave "+1" or …
=> 🚀 Add a new environment variable `TFC_TLS_SKIP_VERIFY`

.github/workflows/end-to-end-tfc.yaml, .github/workflows/end-to-end-tfe.yaml, .github/workflows/helm-end-to-end-tfc.yaml, .github/workflows/helm-end-to-end-tfe.yaml, controllers/module_controller_test.go, controllers/suite_test.go, controllers/workspace_controller_notifications_test.go, controllers/workspace_controller_outputs_test.go, controllers/workspace_controller_test.go
Tests:
- Add the ability to skip TLS certificate validation and align tests with the TFE environment we have in place.
Workflows:
- Update `end-to-end-*` GH workflows to make them less noisy but still efficient whenever there are any changes.
N/A.
```release-note
NONE
```
Depends on: https://github.com/hashicorp/terraform-cloud-operator/pull/222
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original …
=> 🤖 Update tests and related GH test workflows

.github/workflows/helm-end-to-end-tfc.yaml, .github/workflows/helm-end-to-end-tfe.yaml, .github/workflows/unit-tests.yaml, Dockerfile, Makefile, api/v1alpha2/agentpool_validation_test.go, controllers/agentpool_controller_autoscaling.go, controllers/agentpool_controller_deployment.go, controllers/agentpool_controller_test.go, controllers/agentpool_controller_tokens.go, controllers/module_controller_test.go, controllers/workspace_controller_notifications.go, internal/pointer/pointer.go, internal/pointer/pointer_test.go, internal/slice/slice.go, internal/slice/slice_test.go
Move genetic helper functions to `internal/`.
N/A.
```release-note
NONE
```
N/A.
=> 🚀 Move helper functions to `internal/`

CHANGELOG.md, api/v1alpha2/workspace_validation.go, api/v1alpha2/workspace_validation_test.go, controllers/workspace_controller_agents.go, docs/api-reference.md
N/A.
```release-note
`Workspace`: fix an issue when the Operator panics when `spec.executionMode` is configured as `agent` but `spec.agentPool` is not set which is mandatory in this case.
```
Fix: https://github.com/hashicorp/terraform-cloud-operator/issues/241
* If you are …
=> 🐛 Fix panic when `executionMode` is set to `agent` but `agentPool` is not set

CHANGELOG.md, charts/terraform-cloud-operator/templates/deployment.yaml
Bump `kube-rbac-proxy` image from `0.13.1` to `0.14.2`.
N/A.
```release-note
Bump `kube-rbac-proxy` image from `0.13.1` to `0.14.2`.
```
N/A.
=> 🤖 Bump `kube-rbac-proxy` to `0.14.2`

CHANGELOG.md, CONTRIBUTING.md, charts/terraform-cloud-operator/README.md, charts/terraform-cloud-operator/templates/deployment.yaml, charts/terraform-cloud-operator/values.yaml, docs/faq.md
Add the ability to configure `kube-rbac-proxy` image.
Test results:
- https://github.com/hashicorp/terraform-cloud-operator/actions/runs/6483796673/job/17606187384 _TFC_
- https://github.com/hashicorp/terraform-cloud-operator/actions/runs/6483797661/job/17607789674 _TFC + Helm_
- https://github.com/hashicorp/terraform-cloud-operator/actions/runs/6483798887/job/17606193906 _TFE_
- https://github.com/hashicorp/terraform-cloud-operator/actions/runs/6483800064/job/17606196947 _TFE + Helm_
```console
$ helm install ... --set kubeRbacProxy.image.tag=v0.14.3
```
```release-note
ENHANCEMENT:
* `Helm Chart`: Add the ability to configure `kube-rbac-proxy` image.
DOCS:
* Update FAQ. …
```
=> 🚀 Add the ability to configure `kube-rbac-proxy` image

CHANGELOG.md, charts/terraform-cloud-operator/README.md, charts/terraform-cloud-operator/values.yaml
Bump `kube-rbac-proxy` image from 0.14.3 to 0.14.4 that contains Go packages security fixes.
E2E test results: https://github.com/hashicorp/terraform-cloud-operator/actions/runs/6545249283/job/17773333414
N/A.
```release-note
NONE
```
N/A.
* If you are interested in working on …
=> Bump `kube-rbac-proxy` image from 0.14.3 to 0.14.4

Makefile, docs/api-reference.md
Bump [`crd-ref-docs`](https://github.com/elastic/crd-ref-docs) from 0.0.9 to 0.0.10.
Make sure you have the `bin/` folder removed first.
```console
$ make docs
GOBIN=../terraform-cloud-operator/bin go install github.com/elastic/crd-ref-docs@v0.0.10
../terraform-cloud-operator/bin/crd-ref-docs --renderer=markdown --source-path ./api/v1alpha2/ --config=./docs/config.yaml --output-path ./docs/api-reference.md
2023-10-23T18:39:45.652+0200	INFO	crd-ref-docs	Loading configuration	{"path": "./docs/config.yaml"}
2023-10-23T18:39:45.653+0200	INFO	crd-ref-docs	Processing source directory	{"directory": "./api/v1alpha2/", "depth": 6}
2023-10-23T18:39:45.979+0200	INFO	crd-ref-docs	Rendering output	{"path": "./docs/api-reference.md"}
2023-10-23T18:39:45.983+0200	INFO	crd-ref-docs	CRD reference …
```
=> 🌱 Bump crd-ref-docs from 0.0.9 to 0.0.10

.github/dependabot.yml, Dockerfile, go.mod, go.sum
Bump Golang version to 1.21.
N/A.
```release-note
NONE
```
N/A.
=> 🌱 Bump Golang version to 1.21

CHANGELOG.md, controllers/helpers.go, controllers/helpers_test.go, controllers/module_controller_outputs.go, controllers/workspace_controller_outputs.go
Fix an issue of properly handling special characters when generating string output.
Terraform supports the following types:
- https://developer.hashicorp.com/terraform/language/expressions/types
This fix adds logic to handle `string`, `number`, and `bool` types as a string and separates them from `list`, `tuple`, `set`, `map`, and `object` that are treated as a JSON document.
HCL output example:
```hcl
output "multiline_string" {
value     = <<EOT
hello
world
EOT
sensitive = false
}
```
Before:
```yaml
---
apiVersion: v1
kind: ConfigMap
data:
multiline_string: "hello\nworld"
...
```
After:
```yaml
---
apiVersion: v1
kind: ConfigMap
data:
multiline_string: |
hello
world
...
```
Tests:
- https://github.com/hashicorp/terraform-cloud-operator/actions/runs/6667451265 **_TFC_**
N/A.
Release …
=> 🐛 Fix output synchronization

CHANGELOG.md, controllers/agentpool_controller_autoscaling.go, controllers/agentpool_controller_deployment.go
This PR tweaks the logic in the AgentPool controller for autoscaling to take into account plans and applys that are already running when computing the replica count for the agent pool deployment. This PR also sets a default `terminationGracePeriod` on agent deployments to `900` seconds from the default of `30` to allow graceful shutdown of agents that are still busy. 
```release-note
NONE
```
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull- …
=> 🔧 Tweak autoscaler logic

main.go
This change introduces the ability to set the logging level of the operator process through the well-known `TF_LOG` environment variable.
Feel free to suggest a new name for the environment variable if this one is not ideal.
```
TF_LOG=debug ./bin/manager
```
OR
```
kubectl patch deployment <tfc-deployment> -p '{"spec":{"template":{"spec":{containers:[{name:<operator-container>, env:["name": "TF_LOG", "env": "debug"]}]}}'
```
```release-note
* Add ability to set log level via environment variable.
```
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the …
=> Add the ability to configure log levels via env var

api/v1alpha2/agentpool_validation_test.go, api/v1alpha2/module_validation_test.go, api/v1alpha2/workspace_validation_test.go, controllers/module_controller.go, controllers/workspace_controller.go, controllers/workspace_controller_team_access.go
This PR includes some minor issue fixes:
- Make API unit tests run in parallel.
- Fix typos in logs.
- Fix log duplication when a new workspace created.
- Remove unnecessary argument from the `reconcileTeamAccess` method.
N/A.
```release-note
NONE.
```
N/A.
* If you are …
=> 🐛 Fix some minor issues

controllers/workspace_controller_notifications_test.go
Weekly E2E workspace notification tests fail when the list of notifications received from TFC has a different order than notifications in the CR spec, even though all elements match (the slice has the same size, but elements are ordered differently).
This PR fixes this issue.
N/A.
```release-note
NONE
```
Fix: https://github.com/hashicorp/terraform-cloud-operator/issues/311
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and …
=> 🛠️ Fix flaky workspace notification tests

.changes/2.2.0.md, .changie.yaml, .copywrite.hcl, .github/pull_request_template.md, CONTRIBUTING.md, RELEASING.md, scripts/release-date.sh, scripts/update-helm-chart.sh
Migrate changelog management to [Changie](https://changie.dev/).
_With this change, the release process can be further automated within a separate PR._
N/A.
```release-note
NONE.
```
N/A.
* If you are interested in working on this issue or have submitted a pull request, please …
=> 🛠️ Migrate changelog management to Changie

Makefile, RELEASING.md, charts/terraform-cloud-operator/README.md, charts/terraform-cloud-operator/README.md.gotmpl, charts/terraform-cloud-operator/values.yaml
This PR adds the ability to generate Helm chart README file by [helm-docs](https://github.com/norwoodj/helm-docs).
```console
$ make helm-docs
~/bin/helm-docs --log-level=debug --chart-search-root=./charts/terraform-cloud-operator/
DEBU[2024-02-06T14:25:56+01:00] No ignore file found at ~/terraform-cloud-operator/.helmdocsignore, using empty ignore rules
INFO[2024-02-06T14:25:56+01:00] Found Chart directories [.]
DEBU[2024-02-06T14:25:56+01:00] Rendering from optional template files [README.md.gotmpl]
DEBU[2024-02-06T14:25:56+01:00] Rendering from optional template files [README.md.gotmpl]
INFO[2024-02-06T14:25:56+01:00] Generating README Documentation for chart charts/terraform-cloud-operator
DEBU[2024-02-06T14:25:56+01:00] Using template files [README.md.gotmpl] for chart …
```
=> 🛠️ Add `helm-docs` tool to generate Helm chart README file

.github/pr-labeler.yml, .github/workflows/pr-labeler.yml
This PR fixes an issue when all changes get a `documentation` label and bumps `actions/labeler` from `4.0.3` to `4.3.0`.
N/A.
N/A.
=> 🤖 Fix PR labeler GH action

controllers/agentpool_controller.go, controllers/module_controller.go, controllers/predicates.go, controllers/project_controller.go, controllers/workspace_controller.go
This PR adds the ability to add per-controller predicates in addition to the generic predicates that apply to all controllers.
- https://github.com/hashicorp/terraform-cloud-operator/actions/runs/8023783794
- https://github.com/hashicorp/terraform-cloud-operator/actions/runs/8023784632
N/A.
N/A.
* If you are interested in working on this issue or have submitted a pull request, please …
=> 🛠️ Update predicates

controllers/agentpool_controller_test.go, controllers/module_controller_test.go, controllers/project_controller_team_access_test.go, controllers/project_controller_test.go, controllers/suite_test.go, controllers/workspace_controller_agents_test.go, controllers/workspace_controller_notifications_test.go, controllers/workspace_controller_outputs.go, controllers/workspace_controller_outputs_test.go, controllers/workspace_controller_projects_test.go, controllers/workspace_controller_remote_state_sharing_test.go, controllers/workspace_controller_run_tasks_test.go, controllers/workspace_controller_run_triggers_test.go, controllers/workspace_controller_sshkey_test.go, controllers/workspace_controller_team_access_test.go, controllers/workspace_controller_test.go, controllers/workspace_controller_variables_test.go, controllers/workspace_controller_vcs_test.go
Update tests to generate unique names for items. That helps to avoid a situation when tests fail when they run in [envtest](https://book.kubebuilder.io/reference/envtest.html) due to sub-objects(such as `ConfigMap` or `Secret`) are not removed properly. In the future, this will simplify the migration to running tests in parallel.
Tests:
- https://github.com/hashicorp/terraform-cloud-operator/actions/runs/8079447982
- https://github.com/hashicorp/terraform-cloud-operator/actions/runs/8079449466
N/A.
Depends on: https://github.com/hashicorp/terraform-cloud-operator/pull/347
* Please vote on this issue by …
=> 🛠️ Update tests to generate unique names

.changes/unreleased/ENHANCEMENTS-351-20240229-092321.yaml, api/v1alpha2/helpers.go, api/v1alpha2/helpers_test.go, controllers/module_controller.go, controllers/module_controller_outputs.go
This PR brings two related changes:
- Makes the `Module` controller synchronize output when the run status is either `applied` or `planned_and_finished`, whereas previously it was only `applied`.
- Adds `RunCompleted` and `RunApplied` methods to the `RunStatus` structure.
- https://github.com/hashicorp/terraform-cloud-operator/actions/runs/8093096531
- https://github.com/hashicorp/terraform-cloud-operator/actions/runs/8093098023
N/A.
N/A.
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help …
=> 🛠️ Add new Run status methods: `RunCompleted` and `RunApplied`

controllers/workspace_controller_outputs_test.go
This PR moves the create and upload the configuration version step to a separate function to reuse it further.
- https://github.com/hashicorp/terraform-cloud-operator/actions/runs/8094177607
- https://github.com/hashicorp/terraform-cloud-operator/actions/runs/8094178998
N/A.
N/A.
=> 🛠️ Refactor outputs tests

controllers/workspace_controller_notifications_test.go
Revert changes that were made it https://github.com/hashicorp/terraform-cloud-operator/pull/347 since it was reverted on the TFC end.
- https://github.com/hashicorp/terraform-cloud-operator/actions/runs/8111199003
- https://github.com/hashicorp/terraform-cloud-operator/actions/runs/8111199829
N/A.
Revert: https://github.com/hashicorp/terraform-cloud-operator/pull/347
* If you are …
=> 🛠️ Fix Workspace notification tests

.changes/unreleased/ENHANCEMENTS-342-20240215-111818.yaml, .changes/unreleased/NOTES-342-20240215-113038.yaml, api/v1alpha2/workspace_types.go, charts/terraform-cloud-operator/README.md, charts/terraform-cloud-operator/README.md.gotmpl, charts/terraform-cloud-operator/crds/app.terraform.io_workspaces.yaml, config/crd/bases/app.terraform.io_workspaces.yaml, controllers/workspace_controller.go, controllers/workspace_controller_vcs_test.go, docs/api-reference.md
Add the ability to enable or disable automatic speculative plans on pull requests:
- https://developer.hashicorp.com/terraform/cloud-docs/run/ui#speculative-plans-on-pull-requests
- https://developer.hashicorp.com/terraform/cloud-docs/run/remote-operations#speculative-plans
Tests:
- https://github.com/hashicorp/terraform-cloud-operator/actions/runs/8252317239
- https://github.com/hashicorp/terraform-cloud-operator/actions/runs/8252319310
```yaml
apiVersion: app.terraform.io/v1alpha2
kind: Workspace
metadata:
name: this
spec:
...
versionControl:
oAuthTokenID: ot-this
repository: this
speculativePlans: false # THIS IS A NEW OPTION
```
- Close: https://github.com/hashicorp/terraform-cloud-operator/issues/238
* Please do not leave "+1" or other comments that do not add relevant new …
=> 🚀 Add VCS Speculative Plan option

controllers/agentpool_controller.go, controllers/module_controller.go, controllers/project_controller.go, controllers/workspace_controller.go
This PR removes the `getToken` methods and instead switches to the `secretKeyRef` function.
- https://github.com/hashicorp/terraform-cloud-operator/actions/runs/8691664113
- https://github.com/hashicorp/terraform-cloud-operator/actions/runs/8691666287
N/A.
N/A.
=> 🧹 Remove `getToken` methods

api/v1alpha2/workspace_validation.go, controllers/workspace_controller_variables.go
This PR removes the `getValueFrom` method and instead switches to the `configMapKeyRef` and `secretKeyRef` functions.
- https://github.com/hashicorp/terraform-cloud-operator/actions/runs/8691753454
- https://github.com/hashicorp/terraform-cloud-operator/actions/runs/8691755058
N/A.
N/A.
* If you are interested in working on this issue or have submitted a pull request, please leave a …
=> 🧹 Remove `getValueFrom` method

controllers/workspace_controller.go, controllers/workspace_controller_variables.go
This PR adds coverage for an edge case when Workspace does not have variables. This allows making fewer API calls.
- https://github.com/hashicorp/terraform-cloud-operator/actions/runs/8702099213
- https://github.com/hashicorp/terraform-cloud-operator/actions/runs/8702100471
N/A.
N/A.
* If you are interested in working on this issue or have submitted a pull request, please leave a …
=> 🚀 Handle a case when Workspace does not have variables

api/v1alpha2/workspace_validation.go, api/v1alpha2/workspace_validation_test.go
This PR adds `spec.terraformVariables.[*]` and `spec.environmentVariables.[*]` validation.
- https://github.com/hashicorp/terraform-cloud-operator/actions/runs/8708636494
- https://github.com/hashicorp/terraform-cloud-operator/actions/runs/8708639276
N/A.
N/A.
=> 🚀 Add `spec.terraformVariables` and `spec.environmentVariables` validation

.changes/unreleased/FEATURES-391-20240424-100418.yaml, .changes/unreleased/FEATURES-391-20240424-100420.yaml, charts/terraform-cloud-operator/README.md, charts/terraform-cloud-operator/templates/deployment.yaml, charts/terraform-cloud-operator/values.yaml, controllers/flags.go, controllers/workspace_controller.go, docs/faq.md, main.go
This PR introduces a new CLI option called `--workspace-sync-period` along with a corresponding `controllers.workspace.syncPeriod` Helm chart option. It sets the time interval for re-queuing Workspace resources instead of pulling them all at once for reconciliation. This change helps distribute the workload of the Workspace controller more evenly, especially when managing a large number of resources.
```console
$ helm upgrade demo hashicorp/terraform-cloud-operator --set controllers.workspace.syncPeriod=1m
```
N/A. …
=> 🚀 Add `--workspace-sync-period` CLI and corresponding `workspace.syncPeriod` Helm chart option

.changes/unreleased/DEPENDENCIES-392-20240424-095941.yaml, charts/terraform-cloud-operator/README.md, charts/terraform-cloud-operator/values.yaml
Bump kube-rbac-proxy from 0.16.0 to 0.17.0.
N/A.
N/A.
=> 🌱 Bump kube-rbac-proxy from 0.16.0 to 0.17.0

.changes/unreleased/DEPENDENCIES-424-20240606-103613.yaml, charts/terraform-cloud-operator/README.md, charts/terraform-cloud-operator/values.yaml
Bump kube-rbac-proxy from `0.17.0` to `0.18.0`.
- https://github.com/hashicorp/terraform-cloud-operator/actions/runs/9397711209
- https://github.com/hashicorp/terraform-cloud-operator/actions/runs/9397712317
N/A.
- https://github.com/brancz/kube-rbac-proxy/releases/tag/v0.18.0
=> 🌱 Bump kube-rbac-proxy from 0.17.0 to 0.18.0

.changes/unreleased/BUG FIXES-423-20240606-173809.yaml, .changes/unreleased/BUG FIXES-423-20240606-173823.yaml, controllers/module_controller_outputs.go, controllers/workspace_controller_outputs.go
Labels on Kubernetes resources can only be 63 characters long. If the workspace/module name is longer than that, the controllers will go into an error loop. This PR truncates the ConfigMap labels at 63 characters.
I'll be the first to admit this is not a very good solution, and I am open to an alternative. I just didn't want to propose a breaking change without getting some input.
Alternatives:
- Make the labels into annotations instead.
- Do away with the labels entirely.
- Make any or all of the above configurable using CLI flags. 
N/A
- Fixes: #418  …
=> Remove module/workspace name labels from output ConfigMaps

.github/workflows/build.yml, .github/workflows/codeql-analysis.yml, .github/workflows/docker-image-security-scan.yml, .github/workflows/end-to-end-tfc.yaml, .github/workflows/end-to-end-tfe.yaml, .github/workflows/hc-copywrite.yml, .github/workflows/helm-end-to-end-tfc.yaml, .github/workflows/helm-end-to-end-tfe.yaml, .github/workflows/markdown-link-check.yaml, .github/workflows/pr-labeler.yml, .github/workflows/tag-release.yaml, .github/workflows/unit-tests.yaml
Update GH actions to use Node 20, the following actions require updates:
The remaining ones will need to be addressed later
- https://github.com/atlassian/gajira-login
- https://github.com/atlassian/gajira-transition
=> Update GH actions to use Node20

.github/pr-labeler.yml, .github/workflows/pr-labeler.yml
PR Labeler workflow is [failing](https://github.com/hashicorp/terraform-cloud-operator/actions/runs/9461050046/job/26061014339?pr=421) after [action updates](https://github.com/hashicorp/terraform-cloud-operator/pull/406). This PR introduces a fix.
N/A.
- https://github.com/actions/labeler?tab=readme-ov-file#using-configuration-path-input-together-with-the-actionscheckout-action
* If …
=> 🤖 Add repo checkout step to PR labeler workflow

.changes/unreleased/ENHANCEMENTS-432-20240703-130920.yaml, charts/terraform-cloud-operator/README.md, charts/terraform-cloud-operator/templates/deployment.yaml, charts/terraform-cloud-operator/values.yaml
Add default securityContext options. Exposes ability to configure securityContext for:
- manager container
- kube-rbac-proxy container
- entire pod
`values.yaml`
```
securityContext:
runAsNonRoot: true
```
```
operator:
securityContext:
allowPrivilegeEscalation: false
capabilities:
drop:
- ALL
seccompProfile:
type: RuntimeDefault
```
```
kubeRbacProxy:
securityContext:
allowPrivilegeEscalation: false
capabilities:
drop:
- ALL
seccompProfile:
type: RuntimeDefault
```
N/A
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/ …
=> 🚀Add Default `securityContext` and Ability to Configure it

.changes/unreleased/ENHANCEMENTS-420-20240611-101431.yaml, controllers/agentpool_controller.go, controllers/agentpool_controller_autoscaling.go
The `AgentPool` controller re-queues instances every 30 seconds by default even if those that are in the Cool Down period stage and no actions will be taken. This PR changes this logic and instances will be re-queued after the Cool Down period if applicable, otherwise, the default timer is applied.
- https://github.com/hashicorp/terraform-cloud-operator/actions/runs/9462052652
- https://github.com/hashicorp/terraform-cloud-operator/actions/runs/9462053898
- https://github.com/hashicorp/terraform-cloud-operator/actions/runs/9462055264
- https://github.com/hashicorp/terraform-cloud-operator/actions/runs/9462056435
N/A.
- Depends on: https://github.com/hashicorp/terraform-cloud-operator/pull/421
* Please do not leave "+1" or other comments that do not add relevant new information or …
=> 🚀 Update Agent Pool requeue duration logic

controllers/agentpool_controller_autoscaling.go
Fix nil pointer dereference.
_No change log file here, since the issue was found during pre-release and never has been released._
Tests:
- https://github.com/hashicorp/terraform-cloud-operator/actions/runs/9853316599
- https://github.com/hashicorp/terraform-cloud-operator/actions/runs/9853317984
- https://github.com/hashicorp/terraform-cloud-operator/actions/runs/9853319782
- https://github.com/hashicorp/terraform-cloud-operator/actions/runs/9853321271
N/A.
- https://github.com/hashicorp/terraform-cloud-operator/actions/runs/9852993826/job/27202598397 …
=> 🐛 Fix nil pointer dereference

.changes/unreleased/BUG FIXES-426-20240606-184719.yaml, .changes/unreleased/BUG FIXES-426-20240606-184749.yaml, .changes/unreleased/BUG FIXES-426-20240606-184753.yaml, controllers/module_controller_outputs.go, controllers/project_controller_team_access.go, controllers/workspace_controller_agents.go, controllers/workspace_controller_notifications.go, controllers/workspace_controller_outputs.go, controllers/workspace_controller_projects.go, controllers/workspace_controller_remote_state_sharing.go, controllers/workspace_controller_run_tasks.go, controllers/workspace_controller_run_triggers.go, controllers/workspace_controller_sshkey.go, controllers/workspace_controller_team_access.go, controllers/workspace_controller_variables.go
We encountered a bug where some workspaces that should have had run triggers added by the operator did not have them. We suspected it was due to the controller [not handling pagination](https://github.com/hashicorp/terraform-cloud-operator/blob/e7e491c3685dd445d17090fb667a8935f51e3588/controllers/workspace_controller_run_triggers.go#L31). I'm no longer sure that's the source of our bug, but it still seems reasonable that any calls to a Terraform Cloud API endpoint that is paginated should handle that pagination.
N/A
N/A …
=> Handle API pagination

controllers/workspace_controller_notifications_test.go, controllers/workspace_controller_test.go
Fix Notifications tests.
- [![E2E on HCP Terraform Operator](https://github.com/hashicorp/hcp-terraform-operator/actions/workflows/end-to-end-tfc.yaml/badge.svg?branch=fix-notifications-test&event=workflow_dispatch)](https://github.com/hashicorp/hcp-terraform-operator/actions/workflows/end-to-end-tfc.yaml?query=branch:fix-notifications-test)
- [![E2E on HCP Terraform Operator [Helm]](https://github.com/hashicorp/hcp-terraform-operator/actions/workflows/helm-end-to-end-tfc.yaml/badge.svg?branch=fix-notifications-test&event=workflow_dispatch)](https://github.com/hashicorp/hcp-terraform-operator/actions/workflows/helm-end-to-end-tfc.yaml?query=branch:fix-notifications-test)
- [![E2E on Terraform Enterprise](https://github.com/hashicorp/hcp-terraform-operator/actions/workflows/end-to-end-tfe.y …
=> 🤖 Fix Notifications tests

.changes/unreleased/BUG FIXES-460-20240805-123610.yaml, controllers/predicates.go, controllers/workspace_controller.go
In the [originally reported issue](https://github.com/hashicorp/hcp-terraform-operator/issues/440), a third-party controller adds its finalizer to a newly created CR which leads to failure during reconciliation(please refer to the original issue for more details). [This](https://github.com/hashicorp/hcp-terraform-operator/pull/457) PR fixed this issue, however, during development, I found that deleted CR is also affected by a third-party finalizer being added. If CR is marked as deleted and has a third-party finalizer, the workspace will be removed but then it will be created again without the ability to remove it.
This PR updates predicates to filter out events that have a deletion timestamp (CR marked as deleted) and do not have the Workspace finalizer. In addition to that, a new …
=> 🐛 Update Workspace predicate logic

.changes/unreleased/FEATURES-479-20240830-090526.yaml, .changes/unreleased/FEATURES-479-20240830-090626.yaml, charts/hcp-terraform-operator/README.md, charts/hcp-terraform-operator/templates/deployment.yaml, charts/hcp-terraform-operator/values.yaml, controllers/flags.go, controllers/project_controller.go, docs/faq.md, main.go
This PR introduces a new CLI option called `--project-sync-period` along with a corresponding `controllers.project.syncPeriod` Helm chart option. It sets the time interval for re-queuing Project resources instead of pulling them all at once for reconciliation. This change helps distribute the workload of the Project controller more evenly, especially when managing a large number of resources.
- [![E2E on HCP Terraform Operator](https://github.com/hashicorp/hcp-terraform-operator/actions/workflows/end-to-end-tfc.yaml/badge.svg?branch=add-project-sync-period&event=workflow_dispatch)](https://github.com/hashicorp/hcp-terraform-operator/actions/workflows/end-to-end-tfc.yaml?query=branch:add-project-sync-period)
- [![E2E on HCP Terraform Operator …
=> 🚀 Add `--project-sync-period` CLI option

.changes/unreleased/FEATURES-480-20240830-091412.yaml, .changes/unreleased/FEATURES-480-20240830-091446.yaml, charts/hcp-terraform-operator/README.md, charts/hcp-terraform-operator/templates/deployment.yaml, charts/hcp-terraform-operator/values.yaml, controllers/flags.go, controllers/module_controller.go, docs/faq.md, main.go
This PR introduces a new CLI option called `--module-sync-period` along with a corresponding `controllers.module.syncPeriod` Helm chart option. It sets the time interval for re-queuing Module resources instead of pulling them all at once for reconciliation. This change helps distribute the workload of the Module controller more evenly, especially when managing a large number of resources.
- [![E2E on HCP Terraform Operator](https://github.com/hashicorp/hcp-terraform-operator/actions/workflows/end-to-end-tfc.yaml/badge.svg?branch=add-module-sync-period&event=workflow_dispatch)](https://github.com/hashicorp/hcp-terraform-operator/actions/workflows/end-to-end-tfc.yaml?query=branch:add-module-sync-period)
- [![E2E on HCP Terraform Operator …
=> 🚀 Add `--module-sync-period` CLI option

api/v1alpha2/workspace_validation_test.go, controllers/workspace_controller_notifications_test.go, controllers/workspace_controller_run_tasks_test.go
Update the URL in tests to `https://www.hashicorp.com` since `https://example.com` started returning 405 error code.
- [![E2E on HCP Terraform Operator](https://github.com/hashicorp/hcp-terraform-operator/actions/workflows/end-to-end-tfc.yaml/badge.svg?branch=fix-tests&event=workflow_dispatch)](https://github.com/hashicorp/hcp-terraform-operator/actions/workflows/end-to-end-tfc.yaml?query=branch:fix-tests)
- [![E2E on HCP Terraform Operator [Helm]](https://github.com/hashicorp/hcp-terraform-operator/actions/workflows/helm-end-to-end-tfc.yaml/badge.svg?branch=fix-tests&event=workflow_dispatch)](https://github.com/hashicorp/hcp-terraform-operator/actions/workflows/helm-end-to-end-tfc.yaml?query=branch:fix-tests)
- [![E2E on Terraform …
=> 🤖 Update URL in tests

.changes/unreleased/ENHANCEMENTS-481-20240830-094816.yaml, .changes/unreleased/NOTES-481-20240830-094502.yaml, api/v1alpha2/workspace_types.go, charts/hcp-terraform-operator/crds/app.terraform.io_workspaces.yaml, config/crd/bases/app.terraform.io_workspaces.yaml, controllers/workspace_controller.go, controllers/workspace_controller_projects.go, controllers/workspace_controller_projects_test.go
Update the default project ID reconciliation logic in the Workspace controller to avoid making an API call each time a workspace object is updated. Since the default project ID is immutable, we can get it and keep in `status.defaultProjectID` for future usage.
- [![E2E on HCP Terraform Operator](https://github.com/hashicorp/hcp-terraform-operator/actions/workflows/end-to-end-tfc.yaml/badge.svg?branch=update-workspace-default-project&event=workflow_dispatch)](https://github.com/hashicorp/hcp-terraform-operator/actions/workflows/end-to-end-tfc.yaml?query=branch:update-workspace-default-project)
- [![E2E on HCP Terraform Operator [Helm]](https://github.com/hashicorp/hcp-terraform-operator/actions/workflows/helm-end-to-end-tfc.yaml/badge.svg?branch=update-workspace-default-project&event=workfl …
=> 🚀 Update Workspace controller default project ID reconciliation logic

.changes/unreleased/ENHANCEMENTS-482-20240830-161222.yaml, controllers/module_controller.go, controllers/module_controller_outputs.go, controllers/module_controller_test.go
This PR updates the reconciliation logic of the Module controller to proceed to the next step once the configuration version is successfully uploaded and fetches the outputs after the run is completed. Previously, after each step, the reconciliation would unconditionally require the object for a specified time. As a result, fetching the outputs could take up to the entire reconciliation interval.
- [![E2E on HCP Terraform Operator](https://github.com/hashicorp/hcp-terraform-operator/actions/workflows/end-to-end-tfc.yaml/badge.svg?branch=update-module-reconciliation-logic&event=workflow_dispatch)](https://github.com/hashicorp/hcp-terraform-operator/actions/workflows/end-to-end-tfc.yaml?query=branch:update-module-reconciliation-logic)
- [![E2E on HCP Terraform Operator …
=> 🚀 Update Module controller reconciliation logic to pick up outputs faster

.changes/unreleased/ENHANCEMENTS-491-20241002-142919.yaml, charts/hcp-terraform-operator/README.md, charts/hcp-terraform-operator/templates/clusterrole.yaml, charts/hcp-terraform-operator/templates/clusterrolebinding.yaml, charts/hcp-terraform-operator/templates/role.yaml, charts/hcp-terraform-operator/templates/rolebinding.yaml, charts/hcp-terraform-operator/values.yaml
This pull request introduces configurable Role-Based Access Control (RBAC) support to the HCP Terraform Operator. 
The following changes have been made:
- **Helm Chart Updates:**
- Added Helm chart value to `values.yaml` file to enable or disable the creation of RBAC resources.
- Modified the Helm templates to conditionally create RBAC resources based on the provided value.
The addition of configurable RBAC support allows users to have more control over the security and permissions of the HCP Terraform Operator. This is particularly useful for environments with strict security requirements or custom RBAC policies.
To enable/disable RBAC creation, set the `rbac.create` value to `true` or `false` in your `values.yaml` file:
```yaml
rbac:
create: true
```
- Addresses issue #490.
* Please do …
=> 🚀Add Configurable RBAC Support

.changes/unreleased/BREAKING CHANGES-470-20240909-090348.yaml, .changes/unreleased/FEATURES-470-20240909-085913.yaml, .changes/unreleased/NOTES-470-20241017-085430.yaml, api/v1alpha2/workspace_types.go, charts/hcp-terraform-operator/README.md, charts/hcp-terraform-operator/README.md.gotmpl, charts/hcp-terraform-operator/crds/app.terraform.io_workspaces.yaml, config/crd/bases/app.terraform.io_workspaces.yaml, controllers/agentpool_controller.go, controllers/module_controller.go, controllers/project_controller.go, controllers/suite_test.go, controllers/workspace_controller.go, controllers/workspace_controller_deletion_policy.go, controllers/workspace_controller_deletion_policy_test.go, controllers/workspace_controller_outputs_test.go, docs/api-reference.md, docs/faq.md
This PR adds a new field `spec.deletionPolicy` to the workspace schema.
`deletionPolicy` defines the strategies for resource deletion in the Kubernetes operator. It controls how the operator should handle the deletion of resources when triggered by a user action or system event.
There are four possible values:
- `retain`: When the custom resource is deleted, the associated workspace is retained.
- `soft`: Attempts to delete the associated workspace only if it does not contain any managed resources.
- `destroy`: Executes a destroy operation to remove all resources managed by the associated workspace. Once the destruction of these resources is successful, the workspace itself is deleted, followed by the removal of the custom resource.
- `force`: Forcefully and immediately deletes the …
=> 🚀 Add deletion policy to Workspace controller

Dockerfile
This PR adds a new Dockerfile target that uses [Red Hat UBI](https://catalog.redhat.com/software/base-images) micro image. The new target aims to pass [preflight](https://github.com/redhat-openshift-ecosystem/openshift-preflight) validation.
N/A.
N/A.
=> 🐳 Update Dockerfile with a new Red Hat UBI image target

.changes/unreleased/ENHANCEMENTS-478-20240822-123848.yaml, .changes/unreleased/NOTES-478-20240822-123914.yaml, api/v1alpha2/workspace_types.go, charts/hcp-terraform-operator/crds/app.terraform.io_workspaces.yaml, config/crd/bases/app.terraform.io_workspaces.yaml, controllers/workspace_controller.go, controllers/workspace_controller_sshkey.go, controllers/workspace_controller_sshkey_test.go
This PR updates Workspace SSH key reconciliation logic to reduce the number of API calls.
- [![E2E on HCP Terraform Operator](https://github.com/hashicorp/hcp-terraform-operator/actions/workflows/end-to-end-tfc.yaml/badge.svg?branch=update-ssh-key-reconciliation&event=workflow_dispatch)](https://github.com/hashicorp/hcp-terraform-operator/actions/workflows/end-to-end-tfc.yaml?query=branch:update-ssh-key-reconciliation)
- [![E2E on HCP Terraform Operator [Helm]](https://github.com/hashicorp/hcp-terraform-operator/actions/workflows/helm-end-to-end-tfc.yaml/badge.svg?branch=update-ssh-key-reconciliation&event=workflow_dispatch)](https://github.com/hashicorp/hcp-terraform-operator/actions/workflows/helm-end-to-end-tfc.yaml?query=branch:update-ssh-key-reconciliation)
- [![E2E on Terraform …
=> 🚀 Update Workspace SSH key reconciliation logic

.github/workflows/docker-image-security-scan.yml
Bump `aquasecurity/trivy-action` to 0.29.0.
N/A.
N/A.
=> 🌱 Bump aquasecurity/trivy-action to 0.29.0

.changes/unreleased/ENHANCEMENTS-495-20241127-090349.yaml, charts/hcp-terraform-operator/README.md, charts/hcp-terraform-operator/templates/deployment.yaml, charts/hcp-terraform-operator/values.yaml
This PR adds the `affinity` and `tolerations` values to the Helm Chart for the deployment of the Operator.
```yaml
operator:
affinity:
nodeAffinity:
requiredDuringSchedulingIgnoredDuringExecution:
nodeSelectorTerms:
- matchExpressions:
- key: kubernetes.io/arch
operator: In
values:
- amd64
tolerations:
- key: "vmtype"
operator: "Equal"
value: "spot"
effect: "NoSchedule"
```
* If you …
=> Feat add tolerations and affinity to operator deployment

Makefile, api/v1alpha2/workspace_types.go, api/v1alpha2/workspace_validation.go, api/v1alpha2/workspace_validation_test.go, charts/hcp-terraform-operator/crds/app.terraform.io_workspaces.yaml, config/crd/bases/app.terraform.io_workspaces.yaml, docs/api-reference.md
This PR fixes the `spec.versionControl` validation in the Workspace controller.
- [![E2E on HCP Terraform Operator](https://github.com/hashicorp/hcp-terraform-operator/actions/workflows/end-to-end-tfc.yaml/badge.svg?branch=fix-validators&event=workflow_dispatch)](https://github.com/hashicorp/hcp-terraform-operator/actions/workflows/end-to-end-tfc.yaml?query=branch:fix-validators)
- [![E2E on HCP Terraform Operator [Helm]](https://github.com/hashicorp/hcp-terraform-operator/actions/workflows/helm-end-to-end-tfc.yaml/badge.svg?branch=fix-validators&event=workflow_dispatch)](https://github.com/hashicorp/hcp-terraform-operator/actions/workflows/helm-end-to-end-tfc.yaml?query=branch:fix-validators)
- [![E2E on Terraform Enterprise](https://github.com/hashicorp/hcp-terraform-operator/actions/wor …
=> 🐛 Fix Workspace `spec.versionControl` validation

.changes/unreleased/BUG FIXES-580-20250321-154528.yaml, internal/controller/agentpool_controller_autoscaling.go, internal/controller/agentpool_controller_autoscaling_test.go, internal/controller/agentpool_controller_deployment.go, internal/controller/helpers_test.go, internal/controller/workspace_controller_deletion_policy_test.go, internal/controller/workspace_controller_outputs_test.go, internal/controller/workspace_controller_runs_test.go
**_[Agent Pool]_** A newly created CR with `minReplicas` set to 0 results in a deployment with one replica, even when there are no pending runs. The deployment will scale down to 0 during the next reconciliation. If there is a pending run at the time of CR creation, the provisioned deployment replica will pick up this run. However, the CR status will remain unchanged until the next scaling event, which, in some cases, may lead to a prolonged period without a status update.
This PR fixes the behavior described above.
- [![E2E on HCP Terraform Operator](https://github.com/hashicorp/hcp-terraform-operator/actions/workflows/end-to-end-tfc.yaml/badge.svg?branch=fix-agent-deployment-issue&event=workflow_dispatch)](https://github.com/hashicorp/hcp-terraform-operator/actions/workflows/end-to-end-t …
=> 🐛 Fix an issue with agent scaling during the first run

.changes/unreleased/DEPENDENCIES-599-20250429-132517.yaml, charts/hcp-terraform-operator/README.md, charts/hcp-terraform-operator/values.yaml
Bump kube-rbac-proxy from 0.19.0 to 0.19.1.
N/A.
N/A.
=> 🌱 Bump kube-rbac-proxy from 0.19.0 to 0.19.1

.changes/unreleased/BUG FIXES-600-20250429-133405.yaml, Dockerfile
Change UBI Docker image from `micro` to `minimal`. The `micro` version does not have any built-in trust TLS chains and thus causes TLS certificate validation issues when it tries to connect to the HCP Terraform/TFE instance.
N/A.
N/A.
=> 🐛 Change UBI Docker image from micro to minimal

.changes/unreleased/ENHANCEMENTS-601-20250429-135741.yaml, charts/hcp-terraform-operator/README.md, charts/hcp-terraform-operator/templates/deployment.yaml, charts/hcp-terraform-operator/values.yaml, charts/test/unit/deployment_test.go
Add the ability to configure environment variables in the deployment.
```console
$ helm upgrade this hashicorp/hcp-terraform-operator --namespace default \
--wait --version 2.9.1 \
--install \
--set operator.env.HTTP_PROXY="http://proxy:3128"
```
Fix: https://github.com/hashicorp/hcp-terraform-operator/issues/547
* If you are interested in working on this issue or have submitted a …
=> 🚀 Add the ability to configure environment variables in the deployment

.changes/unreleased/BUG FIXES-610-20250527-092719.yaml, internal/controller/agentpool_controller_autoscaling.go
Switch to the previous version of the operator v2.9.1.
No.
This PR fixes an issue where the scaled agent is terminated(due to scale-down event) while a run is still active. This can happen during post-apply or post-plan stages, such as Sentinel policy evaluation and others.
- [![E2E on HCP Terraform Operator](https://github.com/hashicorp/hcp-terraform-operator/actions/workflows/end-to-end-tfc.yaml/badge.svg?branch=fix-agent-scaling-status-filtering&event=workflow_dispatch)](https://github.com/hashicorp/hcp-terraform-operator/actions/workflows/end-to-end-tfc.yaml?query=branch:fix-agent-scaling-status-filtering)
- [![E2E on HCP Terraform Operator …
=> 🐛 Fix the early agent termination issue

.changes/unreleased/BUG FIXES-629-20250804-183959.yaml, internal/controller/workspace_controller_variables.go, internal/controller/workspace_controller_variables_test.go
If a change needs to be reverted, we will publish an updated version of the library.
No.
Fix an issue where sensitive Terraform or Environment variables are not updated when their sensitivity changes.
- [![E2E on HCP Terraform Operator](https://github.com/hashicorp/hcp-terraform-operator/actions/workflows/end-to-end-tfc.yaml/badge.svg?branch=bug-fix-workspace-vars&event=workflow_dispatch)](https://github.com/hashicorp/hcp-terraform-operator/actions/workflows/end-to-end-tfc.yaml?query=branch:bug-fix-workspace-vars)
- [![E2E on HCP Terraform Operator [Helm]](https://github.com/hashicorp/hcp-terraform-operator/actions/workflows/helm-end-to-end-tfc.yaml/badge.svg?branch=bug-f …
=> 🐛 Sensitive variables not updated on sensitivity change

.changes/unreleased/BUG FIXES-618-20250806-133210.yaml, internal/controller/agentpool_controller_autoscaling.go
Switch to a previous version of the operator v.2.9.1.
No.
- Instead of using "non_final" status group which includes runs waiting for user interaction, go back to the previous way of passing in specific statuses.
- Adds in more statuses to cover the issue fixed in GH-610
- Fixes an incorrect log output string
N/A
- Fixes: GH-616
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue …
=> 🐛 Adjust agent scaling algorithm to not include waiting for user interaction statuses
